#!/bin/bash
# $Id$
#
# Debian Packaging Scripts
# Copyright (C) 2002-2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

. ./debian.conf


CHANGELOG_HEADER="`head -n1 debian/changelog`"

PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-Z0-9 ]*(//" -e "s/).*//" -e "s/ //g" -e "s/^[0-9]*://"`
INPUT_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`


echo "######################################################################"
echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
echo "PACKAGE:            $PACKAGE"
echo "INPUT_DISTRIBUTION: $INPUT_DISTRIBUTION"
echo "######################################################################"

sudo echo ""

./clean-deb && \
./make-deb ${INPUT_DISTRIBUTION} && \
DSC_FILE=${PACKAGE}_${PACKAGE_VERSION}~${INPUT_DISTRIBUTION}1~ppa0.dsc && \
sudo pbuilder build $DSC_FILE && \
CHANGES_FILE=/var/cache/pbuilder/result/${PACKAGE}_${PACKAGE_VERSION}~${INPUT_DISTRIBUTION}1~ppa0_*.changes && \
lintian -iIEv --pedantic $CHANGES_FILE
