#!/bin/bash
# $Id$
#
# Debian Packaging Scripts
# Copyright (C) 2002-2011 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

. ./debian.conf


# ---------------------------------------------------------------------------
# USAGE:
# ./make-deb default            => for Ubuntu REVU
#    Note: Replaces "Maintainer" by Ubuntu Developers and
#          writes original maintainer entry to "XSBC-Original-Maintainer"
# ./make-deb unstable           => for Debian Mentors
# ./make-deb natty|maverick|... => for Launchpad PPA
# ---------------------------------------------------------------------------


DISTRIBUTIONS=`\
( \
while [ x$1 != "x" ] ; do \
   echo $1 && \
   shift ; \
done \
) | sort -u`
if [ "$DISTRIBUTIONS" == "" ] ; then
   DISTRIBUTIONS="default"
fi


CHANGELOG_HEADER="`head -n1 debian/changelog`"

PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
OUTPUT_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-Z0-9 ]*(//" -e "s/).*//" -e "s/[0-9]*$//" -e "s/ //g" -e "s/^[0-9]*://"`
UPSTREAM_VERSION=`echo $OUTPUT_VERSION | sed -e "s/-[^ ]*$//g"`
INPUT_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`

echo "######################################################################"
echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
echo "PACKAGE:            $PACKAGE"
echo "UPSTREAM_VERSION:   $UPSTREAM_VERSION"
echo "OUTPUT_VERSION:     $OUTPUT_VERSION"
echo "INPUT_DISTRIBUTION: $INPUT_DISTRIBUTION"
echo "######################################################################"


echo ""
echo "====== Creating upstream package ======================================"
echo ""
UPSTREAM_PACKAGE="`find . -name $PACKAGE-$UPSTREAM_VERSION.tar.gz`"
if [ "$UPSTREAM_PACKAGE" == "" ]; then
   rm -f $PACKAGE-*.gz $PACKAGE"_"*.gz
   echo Running "$MAKE_DIST" ...
   eval "$MAKE_DIST"
   UPSTREAM_PACKAGE="`find . -name $PACKAGE-*.gz`"
   echo ""
   echo "==> Upstream package is $UPSTREAM_PACKAGE"
   echo ""
   if [ ! -e $UPSTREAM_PACKAGE ] ; then
      echo "ERROR: No upstrem package found!"
      exit 1
   fi
fi


echo ""
echo "====== Creating packages =============================================="
for DISTRIBUTION in $DISTRIBUTIONS ; do

   echo ""
   echo "------ Creating package for $DISTRIBUTION ------"

   success=1
   cp $UPSTREAM_PACKAGE $PACKAGE\_$UPSTREAM_VERSION.orig.tar.gz && \
   cp $UPSTREAM_PACKAGE $PACKAGE\_$OUTPUT_VERSION.orig.tar.gz && \
   rm -rf $PACKAGE-$UPSTREAM_VERSION && \
   tar xzf $UPSTREAM_PACKAGE && \
   cp -r debian $PACKAGE-$UPSTREAM_VERSION && \
   find $PACKAGE-$UPSTREAM_VERSION -name .svn | xargs --no-run-if-empty rm -rf && \
   cd $PACKAGE-$UPSTREAM_VERSION && \
   success=0

   if [ $success -ne 0 ] ; then
      exit 1
   fi

   if [ "$DISTRIBUTION" != "default" ] ; then
      if [ "$DISTRIBUTION" = "unstable" -o "$DISTRIBUTION" = "testing" -o "$DISTRIBUTION" = "stable" ] ; then
         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" -e "s/ubuntu[0-9]//1" <debian/changelog >debian/changelog.new
      else
         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" -e "s/ubuntu/ubuntu-$DISTRIBUTION/1" <debian/changelog >debian/changelog.new
      fi
      mv debian/changelog.new debian/changelog

      # ------ Old distributions not supporting new Debian format -----------
      if [ "$DISTRIBUTION" = "dapper" -o "$DISTRIBUTION" = "edgy" -o "$DISTRIBUTION" = "hardy" -o "$DISTRIBUTION" = "intrepid" -o "$DISTRIBUTION" = "jaunty" ] ; then
         rm -rf debian/source
      fi
      # -----------------------------------------------------------------....
   else
      sed -e "s/^Maintainer:/Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>\nXSBC-Original-Maintainer:/g" <debian/control >debian/control.new
      mv debian/control.new debian/control
   fi


   # Without signature!
   # debuild -us -uc
   # For sources:
   # debuild -S
   # For binaries:
   # debuild -b
   # Use -i to ignore .svn files!

   # Including signature!
   # debuild -sa -S -k'Thomas Dreibholz <dreibh@iem.uni-due.de>' -i
   debuild -sa -S "-k$MAINTAINER" -i || exit 1


   # Important: In /etc/pbuilderrc, set COMPONENTS="main universe"!
   # Important: After that, update with option "--override-config"!
   # sudo pbuilder update --override-config

   cd ..

   DSC_FILE="`find . -name $PACKAGE\_$OUTPUT_VERSION-$DISTRIBUTION*.dsc`"
   if [ ! -e $DSC_FILE ] ; then
      echo "ERROR: No $PACKAGE\_$OUTPUT_VERSION-$DISTRIBUTION*.dsc file has been generated -> Aborting!"
      exit 1
   fi

done



echo ""
echo "====== Sign upstream package =========================================="
echo ""
if [ -e "$UPSTREAM_PACKAGE.asc" ] ; then
   rm -f "$UPSTREAM_PACKAGE.asc"
fi
echo "Signing upstream package $UPSTREAM_PACKAGE ..."
gpg -sab "$UPSTREAM_PACKAGE"



echo ""
echo "====== Command overview ==============================================="
echo ""

echo "Upload to PPA:"
for DISTRIBUTION in $DISTRIBUTIONS ; do
   if [ "$DISTRIBUTION" = "unstable" -o "$DISTRIBUTION" = "testing" -o "$DISTRIBUTION" = "stable" -o "$DISTRIBUTION" = "default" ] ; then
      ppa="mentors"
      if [ "$DISTRIBUTION" = "default" ] ; then
         ppa="revu"
      fi
      echo "   dput $ppa `ls $PACKAGE\_$UPSTREAM_VERSION-[0-9]*_source.changes`"
   else
      echo "   dput ppa `ls $PACKAGE\_$OUTPUT_VERSION-$DISTRIBUTION[0-9]_source.changes`"
   fi
done
echo ""

echo "Build test:"
for DISTRIBUTION in $DISTRIBUTIONS ; do
   if [ "$DISTRIBUTION" = "unstable" -o "$DISTRIBUTION" = "testing" -o "$DISTRIBUTION" = "stable" -o "$DISTRIBUTION" = "default" ] ; then
      echo "   sudo pbuilder build `ls $PACKAGE\_$UPSTREAM_VERSION-[0-9]*.dsc`"
   else
      echo "   sudo pbuilder build `ls $PACKAGE\_$OUTPUT_VERSION-$DISTRIBUTION[0-9].dsc`"
   fi
done
echo ""
