#!/usr/bin/env bash
# ==========================================================================
#             ____        _     _   _      _    ____      _
#            / ___| _   _| |__ | \ | | ___| |_ / ___|__ _| | ___
#            \___ \| | | | '_ \|  \| |/ _ \ __| |   / _` | |/ __|
#             ___) | |_| | |_) | |\  |  __/ |_| |__| (_| | | (__
#            |____/ \__,_|_.__/|_| \_|\___|\__|\____\__,_|_|\___|
#
#                    ---  IPv4/IPv6 Subnet Calculator  ---
#                   https://www.nntb.no/~dreibh/subnetcalc/
# ==========================================================================
#
# SubNetCalc - IPv4/IPv6 Subnet Calculator
# Copyright (C) 2024-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu


TEST=
# valgrind

make

$TEST ./subnetcalc 10.1.1.1 32
$TEST ./subnetcalc 10.1.1.1 24
$TEST ./subnetcalc 10.1.1.1 31
$TEST ./subnetcalc 10.1.1.1 255.255.255.255

$TEST ./subnetcalc fd01:1122:3344:affe:0102:03ff:fe04:0506 ffff:ffff:ffff:ffff::
$TEST ./subnetcalc fd01:1122:3344:affe:0102:03ff:fe04:0506 56
$TEST ./subnetcalc fd01:1122:3344:affe:0102:03ff:fe04:0506 ffff:ffff:ffff::
$TEST ./subnetcalc fd01:1122:3344:affe:0102:03ff:fe04:0506 64

$TEST ./subnetcalc fd01:1122:3344:affe:0102:03ff:fe04:0506 64 -uniquelocalhq
$TEST ./subnetcalc fd01:1122:3344:affe:0102:03ff:fe04:0506 64 -uniquelocal

$TEST ./subnetcalc ff02::1:ff11:2233 104
$TEST ./subnetcalc ff3e:0::123:4 128

$TEST ./subnetcalc 64:ff9b::1.2.3.4 96 -n
$TEST ./subnetcalc 64:ff9b:1:2:3:4:5.6.7.8 96 -n

$TEST ./subnetcalc www.heise.de 24
